# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-11 11:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='upvoted_by',
            field=models.ManyToManyField(blank=True, related_name='questions_upvoted', to=settings.AUTH_USER_MODEL),
        ),
    ]
