# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-18 03:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('question', '0002_auto_20160311_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=1000)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers_created', to=settings.AUTH_USER_MODEL)),
                ('question_answered', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers_given', to='question.Question')),
            ],
        ),
    ]
